version: "3"

services: 
    # mysql: 
    #     build: .
    #     ports: 
    #         - 3307:3306

    workspace: 
        image: ghcr.io/maastrichtu-ids/jupyterlab:latest
        ports: 
            - 8888:8888
        environment:
            JUPYTER_TOKEN: pass
        volumes:
            - ./:/home/jovyan/work